# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sneakers?characterEncoding=utf-8&serverTimezone=Asia/Shanghai